name: CoreApp
options:
  bundleIdPrefix: com

configs:
  Debug.Dev: debug
  Debug.Prod: debug
  Release: release

targets:
  core_app:
    type: application
    platform: iOS
    deploymentTarget: 16.4
    settings:
      base:
        MARKETING_VERSION: 1.0
    sources:
       - path: ./source_code
    info:
      path: ./source_code/Info.plist
      properties:
        CFBundleVersion: "1"
        CFBundleShortVersionString: $(MARKETING_VERSION)
        LSRequiresIPhoneOS: YES
        UILaunchScreen: ""
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: YES
        UISupportedInterfaceOrientations~iphone:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad:
          [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
    postCompileScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftformat > /dev/null; then
                  swiftformat .
                else
                  echo "warning: SwiftFormat not installed, download from https://github.com/nicklockwood/SwiftFormat"
                fi
        name: Run SwiftFormat
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                  swiftlint .
                else
                  echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        name: Run SwiftLint
